# Generated by Django 3.2.25 on 2024-04-01 07:58

import django.core.validators
from django.db import migrations, models
import time


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationTime', models.IntegerField(blank=True, default=time.time, null=True, verbose_name='creationTime')),
                ('lastUpdateTime', models.IntegerField(blank=True, default=time.time, null=True, verbose_name='lastUpdateTime')),
                ('name', models.CharField(max_length=200)),
                ('pwd', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('phone', models.CharField(max_length=11, unique=True)),
                ('age', models.SmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)])),
                ('address', models.CharField(default='unkown address', max_length=200)),
                ('gender', models.SmallIntegerField(choices=[(0, 'FEMAIL'), (1, 'MAIL'), (2, 'UNKONWN')], default=2)),
            ],
            options={
                'verbose_name': 'users',
                'verbose_name_plural': 'users',
                'db_table': 'users',
            },
        ),
    ]
